### ISSUE TITLE
installation error on mac

### ISSUE THREAD

**Issue by zhaottcrystal** [JohannesBuchner/RMultiNest#4]
Hi Johannes,

   I have encountered some error when I try to install RMultiNest on a mac machine. I am using a mac with Yosemite system of version 10.10.3. 
   I am following the manual installations steps 2-6. I encountered the error when I was doing ./configure && make Rconnection.o.  The errors are as below:  is there anything I can do to fix it? Thank you very much for your time and patience!

    Rconnection.cc:174:10: error: no member named 'dof' in 'phdr'
    head.dof=ptoi(head.dof);
    ~~~~ ^
Rconnection.cc:174:24: error: no member named 'dof' in 'phdr'
    head.dof=ptoi(head.dof);
                  ~~~~ ^
./Rsrv.h:403:18: note: expanded from macro 'ptoi'
#define ptoi(X) (X)
                 ^
Rconnection.cc:176:14: error: no member named 'dof' in 'phdr'
    if (head.dof>0) { // skip past DOF if present
        ~~~~ ^
Rconnection.cc:178:20: error: no member named 'dof' in 'phdr'
        int k=head.dof;
              ~~~~ ^
Rconnection.cc:238:10: error: no member named 'dof' in 'phdr'
    head.dof=itop(head.dof);
    ~~~~ ^
Rconnection.cc:238:24: error: no member named 'dof' in 'phdr'
    head.dof=itop(head.dof);
                  ~~~~ ^
./Rsrv.h:402:18: note: expanded from macro 'itop'
#define itop(X) (X)
                 ^
Rconnection.cc:246:10: error: no member named 'dof' in 'phdr'
    head.dof=ptoi(head.dof);
    ~~~~ ^
Rconnection.cc:246:24: error: no member named 'dof' in 'phdr'
    head.dof=ptoi(head.dof);
                  ~~~~ ^
./Rsrv.h:403:18: note: expanded from macro 'ptoi'
#define ptoi(X) (X)
                 ^

**Comment by JohannesBuchner** [comment]
Hi @zhaottcrystal ,

Try to download and install Rserve manually from http://www.rforge.net/Rserve/ . 
Open a bug there if you can not compile it. 
I don't know what the error you are getting means -- I also have never tried to compile it on MacOS.
As a last resort, you could use a Linux installation inside Virtualbox.

Cheers,
              Johannes

**Comment by zhaottcrystal** [comment]
I see! I actually download and install Rserve manually as you suggest. I will try use a Linux installation then, which seems more reliable than mac! Thank you very much! :) I have made the pymultinest work just now. If this R version does not work, it is also fine then.:) Very useful package, thanks for your great work!

Best,
Crystal

**Comment by JohannesBuchner** [comment]
No worries
